---
layout: default
title: Jekyll-Asciidoc Quickstart
description: A forkable blog-ready Jekyll site using Asciidoc
documentationExpanded: false
postsExpanded: false
---

= Congratulations!

You've successfully set up and deployed an Jekyll website powered by Asciidoc using the https://github.com/asciidoctor/jekyll-asciidoc-quickstart[*Asciidoc-Jekyll-Quickstart*] project.  If everything is in order then changes to the Asciidoc content will be automatically published to your `gh_pages` branch and hosted via Jekyll and Github.

== What do I do now?

Now that you've set up your website to run with Asciidoc you have a ton of options available to you.

==== Edit content
Editing content is very simple.  The easiest way to update your blog is to clone your repository, fire up your favorite text editor and run the content locally.  To do this run the `jekyll serve` command and open a web browser to http://localhost:4000.  Jekyll will automatically process and host changes to the content.

You may also edit your content directly on Github.  To do this, navigate the browser the file you wish to edit, click the pensil (edit) button in the upper right hand corner of the view and make your changes.  When you're finished, commit your changes.  This will trigger Travis to generate and publish a new website including your changes.

For blog posts, Jekyll will recognize files under the `_post` directory, parse the name and place it in the list of posts.  These will show up under the `site.posts` variable.

To display a list of posts, use Jekyll syntax similar to the following:

[source, html]
--
{% raw %}
{% for post in site.posts limit: 5 %}
    <a href=".{{ post.url }}">{{ post.shortTitle }}</a>
{% endfor %}
{% endraw %}
--


==== Update Look and feel
The layout provided with the https://github.com/asciidoctor/jekyll-asciidoc-quickstart[Jekyll-Asciidoc Quickstart] project is based on http://foundation.zurb.com[Foundation], a responsive design css framework.  You're free to update the layout by editing the `_layouts/default.html` file and css under the `css` directory.

This blog layout is based on the http://foundation.zurb.com/templates/blog.html[Blog template].

==== Reference documentation
The following links will help with detailed explanations on Jekyll and Asciidoc.

http://jekyllrb.com[Jekyll]
http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[Asciidoc Quick Reference]
http://asciidoctor.org[Asciidoctor]

