= Jekyll AsciiDoc Quickstart
:numbered:
:website-url: http&#58;//your-github-username.github.io/name-of-this-repository
ifndef::env-github[:toc:]

The Jekyll AsciiDoc Quickstart project is a leg-up in starting your own website hosted on GitHub with content based in AsciiDoc. This project combines the power of AsciiDoc with a beautiful CSS framework and blog-ready template on top of GitHub's existing publishing infrastructure.

It has a GitHub Action workflow to listen for commits on the `master` or `main` branch, automatically run the Jekyll build and push the generated content to the `gh-pages` branch to publish your website. 

== Directions

=== Fork this Repository and Configure GitHub Pages

. Click the `Fork` button in the upper right corner of GitHub to create your own copy of this repository.
. After the fork is completed and you are redirected to your own repository copy:
.. Access the `Settings` tab, then the `Pages` left menu.
.. In the  `source` field, select the `gh-pages` branch to be the source of the website files (this branch is where the Jekyll build will place the generated files). 
.. Finally, click the `save` button and return to your respository home.

=== Verify the Build/Publish

After every push, the GitHub Action workflow is automatically started to build and publish your website.
That takes a while. You can wait to see a ✅ at the top of your repository home.

If you can load the `{website-url}` home page, you have successfully completed the basic configuration.
Start writing blog posts and enjoy the AsciiDoc difference, regardless of what device you choose: computer, tablet, or mobile.

== Run your Website Locally

You must install some software to build and serve your website locally. The requirements on the http://jekyllrb.com/docs/installation/[Jekyll Installation] page describe how to install both ruby and rubygems.

If you would like to work offline first, consider to check your `Gemfile` for the versions of your gem sources. As the case may be, your `jekyll serve` will fail. So make sure to check your gem sources with `gem list --local | grep "jekyll"`.


== GitHub Pages and AsciiDoc

GitHub Pages does not (yet) whitelist the jekyll-asciidoc plug-in, so you can not write `.adoc` posts and have them instantly published like Markdown posts do. However, the only additional thing we need is the link:.github/workflows/publish.yml[publish.yml] workflow which is already configured. You don't have to change it, unless you want to perform some customization in the build/publish process.

=== Help Get AsciiDoc Whitelisted for GitHub Pages

You can help change the lack of native AsciiDoc support by creating a support case through http://github.com/support.
This way, we won't need a GitHub Action workflow anymore to publish AsciiDoc websites.

Tell the GitHub team that you want the choice to write in AsciiDoc, and have it handled the same way Markdown is when pushed to your GitHub Page.

Your voice counts: make it heard!

== Repository Structure

The repository requires the following structure to work correctly:

* **master**, for markup sources and configuration. This branch can be named anything you choose, however **master** is a general standard used in Jekyll blogs.
* **gh-pages**, for the generated static content produced by Travis CI. This branch is the username.github.io GitHub Pages domain, which is created automatically for you when the Travis CI job runs.
