= What's new in relm 0.10.0?
:page-navtitle: What's new in relm 0.10.0?

Relm is an attempt to do an idiomatic GUI library in Rust, based on gtk+ and tokio.
See the link:{{ site.baseurl }}/relm-intro[introduction article] for details about why this library was created and how to use it.

This new release is huge: a lot of changes happened under the hood, the API was changed and features that were unsound were removed.
The https://github.com/antoyo/titanium[web browser titanium] has been updated to use this latest version of relm.
The journey has not been without pitfalls and some convenient features of relm were removed because they caused issues.

== Removed features

=== Shared model

The model is no longer a shared.
In the previous versions of relm, it was a `Rc<RefCell<Model>>` for convenience:
it was possible to share a model with a gtk+ callback for instance.
However, when developing titanium, I've again got bitten by the infamous borrow mut error at runtime, while this was precisely link:{{ site.baseurl }}/relm-intro#state-mutation[one issue] relm tries to solve.
Now, there's a single owner to a widget's model and the only way to mutate the model is through its widget:
if we want to update the model from another widget, we need to send a message to the other widget.

=== Synchronous callbacks

Also, the feature allowing to use synchronous callbacks in an asynchronous way were removed because they do not fit well within the model of relm, where everything is asynchronous.
While this feature was convenient because it allowed to return a value to a gtk+ callback from within a widget's update method, it was removed because it could cause slowdown if abused and mainly because it was unsound.
Remember that the update method takes `self` by mutable reference, and with this feature, it was possible to block an event handling, while it was waiting for the widget to resolve the value to be returned to the gtk+ callback.
So, if the event was triggered twice, it could be possible to have two `&mut` over the model.
That's a pretty bad thing that Rust prevents us from doing.

=== Networking examples

This release took a long time to be release.
The reason is that I was waiting for tokio issues to be fixed.
Since I've been waiting for months and they are still not resolved, I decided to release a version without the examples relying on tokio (the http and websockets examples).
And they're not likely to be fixed soon since `tokio-proto` is likely to be https://www.reddit.com/r/rust/comments/6s4axu/asynchronous_rust_complaints_suggestions/dlawxao/[de-emphasize] and it's used both by `hyper` and `twist` (the websockets crate).
That doesn't mean it's not possible to use tokio:
titanium uses tokio, but it needs a special version of the tokio-based crate so that the futures can be spawned on the glib event loop.
In order to be able to use tokio-based crates with relm, they need to be updated to use the new https://docs.rs/futures/newest/futures/executor/trait.Executor.html[Executor trait] instead of relying on the tokio-core `Handle`.

== Switch to futures-glib

During the Rust+GNOME HackFest in Mexico, Alex Crichton and I worked on a way to spawn futures directly on the glib event loop:
the https://github.com/antoyo/futures-glib-rs[futures-glib crate].
Using that, relm now executes only in one thread, which simplify a lot of things while being more efficient.

== Is relm usable on stable Rust?

Yes, it is!
And you can even benefit from the nice syntax by using the https://github.com/antoyo/relm/blob/master/examples/buttons-derive/src/main.rs#L49[`relm_widget!` macro].

== Projects using relm

There's already a few https://github.com/antoyo/relm#projects-using-relm[projects using relm].
If you use relm, consider posting the link to your project https://github.com/antoyo/relm/issues/30[in this issue].

== New features

Here's other new features of this release, in bulk:

 * https://github.com/antoyo/relm/commit/4356d379cbd7c9aa8d92bb592a5ecd201384f2ec[New `with` syntax to ease sharing a value with a gtk+ callback (to replace the removed synchronous callbacks feature).]
 * https://github.com/antoyo/relm/commit/9b83e1ec9f92bd514edcd92b79fa529e3ab120a1[Separate the `Widget` trait into an `Update` trait to be able to use relm in a non-UI context (which in a new relm-state crate).]
 * https://github.com/antoyo/relm/commit/4b086c3ea7bcfb36c11d941f4d335fb85d926009[New `connect_stream!` macro to be used in a non-UI context.]
 * https://github.com/antoyo/relm/commit/aeebe4e8c09affe1f00354a2c2e7fe78828c2edd[Fix to be able to have messages with multiple values.]
 * https://github.com/antoyo/relm/commit/15204e9b41be8db88cc861a236997bbc56ad4b66[Add the ability to use a message as a property in the view (to be able to update another widget's model conveniently since it is now forbidden to share a widget)]
 * https://github.com/antoyo/relm/commit/c5461e8233b76db7f2b5e20f0cee67f0ded66027[New shortcut method to emit a message on a widget.]
 * https://github.com/antoyo/relm/commit/a70ccadc97f7d1d304c9623f8dddd10d45bd5015[Add support for children events.]
 * New https://github.com/antoyo/relm/commit/8068548a6dd04206e2eb76fa1a2b0a103c9ea8e6[`IntoPair`] and https://github.com/antoyo/relm/commit/f4c4a48ee30b8c3aeabdf32a5af949b08416f309[`IntoOption`] traits for more convenience in signal connections.
 * https://github.com/antoyo/relm/commit/39ea6da0bd3649e53344e777e9e6a9ee7c064424[Add support for construct properties.]
 * https://github.com/antoyo/relm/commit/2abbdc775c540cceafc9e3f49745b2a9b6a2f3e1[Log the generated code to help debugging.]
 * https://github.com/antoyo/relm/commit/26e351385d85f10feb39a14c879143c4b502f40c[Add a stream lock to have a way to avoid infinite event emission.]
 * https://github.com/antoyo/relm/commit/263bfb020d3b01e1ed490bedd7c8d5b15edd939f[Allow adding custom methods in the trait annotated by the widget attribute: this is useful to have other methods than `update` that modify the model, thus automatically updating the view.]
 * https://github.com/antoyo/relm/commit/29a85685dad3a5fb70fc989c7be2be50eab8b954[The model is not a parameter anymore, it is now part of the widget struct.]
 * https://github.com/antoyo/relm/commit/c94c354a3e23527ccfde8e9dc04704ba045afa90[New multi-container feature.]
 * https://github.com/antoyo/relm/commit/49ca37deec56ed5aeb0f818d2dac6799501bd1a8[Add a way to specify additional data to initialize the model.]
 * https://github.com/antoyo/relm/commit/fbf842c14c84fdeaf703cfced3d2203cb0b8e9af[Add support for generic widgets.]
 * https://github.com/antoyo/relm/commit/911c14b39018a8f751c6ac0c3d71cceef7cf0df0[Add support for gtk+ child properties.]
 * https://github.com/antoyo/relm/commit/092ab0606020ae2b0349156e00d29af6b44d5546[Add `init_view()` on the `Widget` trait to be able to execute arbitrary code to update the view when a widget is created: this is useful when using the `view!` macro usable within the widget attribute.]
 * No more `Send` bound for the Model and fewer `Clone` bounds required.
 * Many fixes.

== Need help?

If you need help to use relm, there's a https://gitter.im/relm-rs/Lobby[gitter] and I'm also usually on `#gtk-rs`, `#rust-fr` and the GNOME's `#rust` channel.
You may also open https://github.com/antoyo/relm/issues[an issue on GitHub] to ask questions.

== Future

Beside many issues to be fixed and corner cases of gtk+ to support in relm, the most important thing to improve is the error messages.
Since relm heavily uses code generation, the error message are very bad.
Relm needs to be updated to use the https://github.com/alexcrichton/proc-macro2[proc-macro2] crate in order to be able to keep the position of the tokens in the generated code.
This will require a huge refactor because many things changed in the syn crate.

Comment on https://www.reddit.com/r/rust/comments/6ts036/whats_new_in_relm_0100/[reddit].
